name: Ubuntu Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    name: Build and Test
    steps:
    - name: Prepare
      run: |
        sudo apt-get update -qq
        sudo apt install -y g++ googletest valgrind

    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Configure shell
      # Since we're not compiling on the Beaglebone, disable arm specifics
      run: |
        echo 'ARM_COMPILE_FLAGS=' >> $GITHUB_ENV

    - name: Build
      run: |
        make

    - name: Test
      run: |
        make test

    - name: Valgrind Test
      run: |
        BEAGLEG_OPT_CFLAGS="-O3 -g" make valgrind-test

  Coverage:
    runs-on: ubuntu-latest

    name: Coverage prepare
    steps:
    - name: Prepare
      run: |
        sudo apt-get update -qq
        sudo apt install -y g++ googletest lcov

    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Configure shell
      # Since we're not compiling on the Beaglebone, disable arm specifics
      run: |
        echo 'ARM_COMPILE_FLAGS=' >> $GITHUB_ENV

    - name: Coverage run
      run: |
        make -C src beagleg.coverage

    - name: Upload coverage
      uses: codecov/codecov-action@v2
      with:
        files: src/beagleg.coverage
        fail_ci_if_error: true
        verbose: true

  CodeFormatting:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Dependencies
      run: |
        sudo apt-get install clang-format-11
        clang-format --version

    - name: Run formatting style check
      run: ./.github/bin/run-clang-format.sh
