name: 'main'

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    name: Build and Test
    steps:
    - name: Prepare
      run: |
        sudo apt-get update -qq
        sudo apt install -y g++ googletest

    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Configure shell
      # Since we're not compiling on the Beaglebone, disable arm specifics
      run: |
        echo 'ARM_COMPILE_FLAGS=' >> $GITHUB_ENV

    - name: Build
      run: |
        make

    - name: Test
      run: |
        make test

  CodeFormatting:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Dependencies
      run: |
        sudo apt-get install clang-format
        clang-format --version

    - name: Run formatting style check
      run: ./.github/bin/run-clang-format.sh
